name: Update TV Channels

on:
  schedule:
    - cron: '0 7,17 * * *'   # 每天 7:00 和 17:00 运行
  workflow_dispatch:          # 允许手动触发

permissions:
  contents: write             # 允许推送代码到仓库

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          check-latest: true

      - name: Install dependencies
        run: npm install axios

      - name: Fetch and process M3U
        env:
            M3U_URL: "https://live.ottiptv.cc/iptv.m3u?userid=7576776924&sign=e28ce4449da7c653dc9bc84d0ebe21ff1d66c2d3af3dccf1c5bc9082ea33f6e59bf146b87753f6502e22832269c5bc9cc33907f8a459db4803dbdffaaca3c9b9d44c8fabd072ef&auth_token=4170588d643aa44e389f0bdd82c0d18b"
        run: node process.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tv.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Update tv.m3u [skip ci]"
          git push
